### ISSUE TITLE
"token/" + toWho hatası;

### ISSUE THREAD

**Issue by drstewen** [berkanaslan/flutter_live_chat_app#1]
Merhaba, eğer iznin olursa yazdıklarının bazı kısımlarını kullanmak istiyorum.
``Future<String>` getUserToken(String toWho) async {
    DocumentSnapshot _doc = await _firestore.doc("tokens/" + toWho).get();
    if (_doc != null) {
      Map<String, dynamic> _data = _doc.data();
      return _data["token"];
    } else {
      return null;
    }
  }``
bu kodu yazdığımda;
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (18305): Receiver: null
E/flutter (18305): Tried calling: []("token")
şöyle bir hata alıyorum. 
Ayrıca Cloud Messagingde yeni sürümlerde "configure" metodu kaldırılmış yardımcı olursan sevinirim.

**Comment by berkanaslan** [comment]
Null hatası Firestore collection yapınla alakalı gibi duruyor. Orayı kontrol etmeni tavsiye ederim.
Firebase Messaging için buraya bakabilirsin: https://github.com/FirebaseExtended/flutterfire/tree/master/docs/messaging
